### PR TITLE
#286 - RepoConfig simple implementation and usage in Rpm

### PR DESCRIPTION
**Pull request by olenagerasimova**
For #286 I've created `Simple` implementation of `RepoConfig` and added as parameter to `Rpm` and `RpmSlice`.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/291#issuecomment-648020289))

@olenagerasimova Job `gh:artipie/rpm-adapter#291` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/291#issuecomment-648020289))

@olenagerasimova Pull request [#291](https://github.com/artipie/rpm-adapter/issues/291) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#291` is not assigned, can't get performer

**Pull request merged**
