### PR TITLE
#190 - Throwing InvalidPackageException when package failed to be parsed

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #190 
Throwing InvalidPackageException when package failed to be parsed.
This is required to distinguish bad package from other problems when package is parsed, such as I/O errors

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#212](https://github.com/artipie/rpm-adapter/issues/212) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7f29fde9-6752-40ba-8df8-fa7577dae202); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I see that you unassigned this issue; the order is still assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
This pull request [#212](https://github.com/artipie/rpm-adapter/issues/212) is assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/29366d02-e69c-4674-a164-52e69076ce09); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by olegmoz** [comment]
@olenagerasimova this PR does not close the issue yet, I want to make another PR later to actually use the thrown exception. Do I need to edit puzzle in this case?

**Comment by olenagerasimova** [comment]
@olegmoz yes, this issue will be closed, new one created and you continue the work.

**Comment by olegmoz** [comment]
@olenagerasimova I'd prefer to not close the puzzle with this PR, and make another one later if it's ok

**Comment by olenagerasimova** [comment]
@olegmoz this is not how pdd works, and this repo is managed by 0crat, so I think we should follow the rules: if the issue will not be closed, you will not get the money/reputation. 0pdd will report unsolved puzzles to issues as, for example, here in #200.

**Comment by olegmoz** [comment]
@olenagerasimova ok, got it. Added changes to original puzzle

**Comment by olenagerasimova** [comment]
@g4s8 please merge

**Comment by 0crat** [comment]
Job was finished in 22 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@olenagerasimova please make sure you will find at leat 3 issues during next CR, thanks!

**Comment by olenagerasimova** [comment]
@sereshqua will do my best

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
