### PR TITLE
#203 - add timing extension for tests

### PR DESCRIPTION
**Pull request by olenagerasimova**
For #203 added `TimingExtension` for junit, used it in itcases and removed logging in main classes.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#209](https://github.com/artipie/rpm-adapter/issues/209) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/589efa8c-91af-4bb8-9078-ac621e91302f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by olenagerasimova** [comment]
@paulodamaso thanks, corrected, take a look please

**Comment by paulodamaso** [comment]
@g4s8 please merge

**Comment by olenagerasimova** [comment]
@g4s8 please merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@paulodamaso please make sure you will find at least 3 issues during next CR, thanks!

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
