### PR TITLE
#168 - Test for XmlRepomd

### PR DESCRIPTION
**Pull request by olenagerasimova**
For #168 I've created test for `XmlRepomd` and added simple implementation of `Checksum`.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/300#issuecomment-650945661))

@olenagerasimova Job `gh:artipie/rpm-adapter#300` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/300#issuecomment-650945661))

@olenagerasimova Pull request [#300](https://github.com/artipie/rpm-adapter/issues/300) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#300` is not assigned, can't get performer

**Pull request merged**
