### PR TITLE
refactor(XmlEvent): check if primary file is a directory

### PR DESCRIPTION
**Pull request by baudoliver7**
After analyzing condition according to `createrepo` by which `type=dir` is added, we noticed that we need to compare file mode and a specific flag called `S_IFDIR`. 

Theses changes allowed us to identify some errors in some test resources while executing `XmlEventPrimaryTest`. For example, file `/etc/dbus-1/session.d` in `XmlEventPrimaryTest/dbus_res.xml` was considered as regular file instead of directory.
We fixed them all.

We also added a puzzle to resolve the case when file is a `ghost`, noting that the default type is `regular` (empty value)

Fix: #501

### CODE REVIEW

**Comment by baudoliver7** [comment]
@artipie/maintainers ready to be reviewed :)

**Review by olenagerasimova — COMMENTED** [review]
@baudoliver7 thanks, changes look good. Though I do not understand, why are we linking to the `iOS Manual Pages`? Is not this `S_IFDIR` constant declared somewhere in createrepo code?

**Comment by baudoliver7** [comment]
> @baudoliver7 thanks, changes look good. Though I do not understand, why are we linking to the `iOS Manual Pages`? Is not this `S_IFDIR` constant declared somewhere in createrepo code?

`S_IFDIR` come from `glibc` library (see [Official documentation](https://man7.org/linux/man-pages/man7/inode.7.html)).
I updated the link.
I took the opportunity to refactor condition of directory accordance to the documentation.

**Review by olenagerasimova — APPROVED** [review]
@baudoliver7 thanks, merging

**Pull request merged**
