### PR TITLE
#205 - Add more tests for CliArgumentTests

### PR DESCRIPTION
**Pull request by marceloamadeu**
This PR is for #205:

- Added new tests for `CliArgument` with **'='** signal

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#211](https://github.com/artipie/rpm-adapter/issues/211) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b2555bf0-7ce3-4820-a39a-2a88846f620a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@marceloamadeu Looks great, but we still miss the arguments in `longopt` form, please add the remaining tests

**Comment by paulodamaso** [comment]
@marceloamadeu Also, I think that the test names would be better if you use `Equals` instead of `Signal` at the end and intruduce the word `Sent`, like, `canParseNamingPolicyArgumentWithSignal` would be `canParseNamingPolicyArgumentSentWithEquals`, WDYT?

**Comment by paulodamaso** [comment]
@marceloamadeu Why the changes in `pom.xml`, `MetadataFileTest.` and `NamingPolicy`?

**Comment by marceloamadeu** [comment]
@paulodamaso Corrections made, take a look.

**Comment by paulodamaso** [comment]
@g4s8 please merge

**Comment by 0crat** [comment]
Job was finished in 38 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Pull request merged**
