### PR TITLE
Avoid to upload unused XML files to storage

### PR DESCRIPTION
**Pull request by brastak**
For #45

### CODE REVIEW

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/46#issuecomment-601628042))

@g4s8 Job `gh:artipie/rpm-adapter#46` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#46` doesn't exist in WBS, can't create order

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#46` is not assigned, can't get performer

**Pull request merged**
