### PR TITLE
#117 added two tests for xmlprimary

### PR DESCRIPTION
**Pull request by ammaratef45**
PR for #117 
Added some tests and a puzzle for adding more tests

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#156](https://github.com/artipie/rpm-adapter/issues/156) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/57f8fc97-d11d-4282-b24a-7dd8c477aeb6); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@g4s8 
`ERROR: Puzzle src/main/java/com/artipie/rpm/meta/XmlAlter.java:45-46 has a very short description of just 14 words while a minimum of 15 is required`

This file isn't edited by me, what should I do with this?

**Comment by g4s8** [comment]
@ammaratef45 this linter is not yet required, I'll fix it before enforcing this check

**Comment by Vatavuk** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@ammaratef45 please check some build errors

**Comment by ammaratef45** [comment]
@g4s8 
`[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:check (jacoco-check) on project rpm-adapter: Coverage checks have not been met. See log for details. -> [Help 1]`
Is this related to the word I did here somehow?

**Comment by Vatavuk** [comment]
@ammaratef45 @g4s8 ping

**Comment by Vatavuk** [comment]
@ammaratef45 please respond

**Comment by ammaratef45** [comment]
@Vatavuk @g4s8 The task is resigned from me, should I close the PR?

**Comment by olenagerasimova** [comment]
@ammaratef45 @Vatavuk #117 is already closed, I'm closing this PR

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#156` is not assigned, can't get performer

**Pull request closed without merging**
