### PR TITLE
resolve #35

### LINKED ISSUE #35: Add test for RepoXML

### PR DESCRIPTION
**Pull request by Guseyn**
Implemented unit test for Repomd: #35

### CODE REVIEW

**Comment by g4s8** [comment]
@Guseyn can you please use a bit more verbose PR descriptions and titles to understand the reason of PR without switching to code tab? E.g. "Implemented unit test for Repomd" would be enough. Also, it would be good to put a link for ticket in PR body - Github automatically creates a link in ticket to this PR.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#38` is not assigned, can't get performer

**Comment by 0crat** [comment]
This pull request [#38](https://github.com/artipie/rpm-adapter/issues/38) is assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e0576e38-805f-4a53-b56f-3274029e252b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@cbab2ca4a324, thread: PQ-CT2E6TK9B
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.51.12](https://github.com/zerocracy/farm): CID: [52257a97-72ac-441b-a90b-c7a568af4ea3](https://www.0crat.com/footprint/CT2E6TK9B/52257a97-72ac-441b-a90b-c7a568af4ea3), Type: "Order was canceled"

**Comment by 0crat** [comment]
@dgarus[/z](https://www.0crat.com/u/dgarus) resigned from [#38](https://github.com/artipie/rpm-adapter/issues/38), since the job is not in scope anymore

**Pull request merged**
