### PR TITLE
Updated http and asto version

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated http and asto version, used new features where possible.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@victornoel thanks, done

**Comment by olenagerasimova** [comment]
@g4s8 please approve/merge

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @victornoel[/z](https://www.0crat.com/u/victornoel)[/z](https://www.0crat.com/u/victornoel) didn't make CR comments

**Pull request merged**
