### PR TITLE
One more javadoc fix

### PR DESCRIPTION
**Pull request by olenagerasimova**
Fix javadoc again to [release](https://github.com/artipie/rpm-adapter/pull/367#issue-492317560)

### CODE REVIEW

**Comment by olegmoz** [comment]
@olenagerasimova I have created ppom `0.4.1` with downgrade of all plugins to previously used versions, so CI checks will be same as in rultor. Otherwise we will fix XML files, JavaDocs and other things for every release

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#367` is not assigned, can't get performer

**Pull request merged**
