### PR TITLE
Added github action for benchmarks

### LINKED ISSUE #382: RPM benchmarks
Add benchmarks for RPM repository:
 - update a single package (100, 1000, 5000)
 - batch-update (100, 1000, 5000)

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #382 
Added github action to build benchmarks.

### CODE REVIEW

**Review by genryxy — APPROVED** [review]
@olenagerasimova thanks, looks good to me

**Review by g4s8 — CHANGES_REQUESTED** [review]
@olenagerasimova maybe we can just add this to existing build workflow? https://github.com/artipie/rpm-adapter/blob/master/.github/workflows/maven.yml

**Comment by olenagerasimova** [comment]
@g4s8 thanks, done

**Comment by g4s8** [comment]
@olenagerasimova now build is failing

**Comment by olenagerasimova** [comment]
@g4s8 corrected, thanks

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks

**Pull request merged**
