### PR TITLE
320 OthersOutputTest added

### PR DESCRIPTION
**Pull request by genryxy**
For #320 OthersOutputTest added

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@genryxy could you please merge master to make this branch up-to-date?

**Comment by g4s8** [comment]
@genryxy @olenagerasimova it seems GitHub can't automatically merge `master` branch here, @genryxy please do it manually with these commands:
```
git checkout 320_othersOutputTest
git fetch upstream master:master
git merge --no-ff master
# resolve conflicts if needed
git push origin 320_othersOutputTest
```

**Comment by genryxy** [comment]
@olenagerasimova @g4s8 I had outdated master in forked repo. 
thanks

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#338` is not assigned, can't get performer

**Comment by 0crat** [comment]
You @genryxy[/z](https://www.0crat.com/u/genryxy) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Pull request merged**
