### PR TITLE
#340 - Using lock with expiration for RPM batch update

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #340 
Using lock with expiration for RPM batch update

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@olegmoz thanks, looks good to me, one question: are you planning to add locks to incremental update in the next PR?

**Comment by olegmoz** [comment]
@olenagerasimova yes, I am planning to add locking to incremental update in next PR. After that I'd consider the task done.

**Review by olenagerasimova — APPROVED** [review]
@olegmoz thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#341` is not assigned, can't get performer

**Pull request merged**
