### PR TITLE
Created `XmlPrimaryComposition` to append packages to primary.xml

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #388 
Created `XmlPrimaryComposition` to append packages to primary.xml, return checksums of the duplicated packages and count resulting items in the primary.xml.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@g4s8 could you please review this PR? I need it merged to continue the work

**Review by g4s8 — CHANGES_REQUESTED** [review]
@olenagerasimova thanks, the overall changes are good, but I don't really understand class name `XmlPrimaryComposition`, maybe we can use a more obvious name?

**Comment by olenagerasimova** [comment]
@g4s8 hm, the class composes new primary xml index based on the given primary xml (as input stream) and new rpms (provided as file list), so the result is some sort of composition of the provided data. Maybe, method name is not very suitable?

**Comment by olenagerasimova** [comment]
@g4s8 what do you say?

**Comment by g4s8** [comment]
> @g4s8 hm, the class composes new primary xml index based on the given primary xml (as input stream) and new rpms (provided as file list), so the result is some sort of composition of the provided data. Maybe, method name is not very suitable?

@olenagerasimova what do you think about `MergedPrimaryXml` or something similar?

**Comment by olenagerasimova** [comment]
@g4s8 seems good, renamed, thanks

**Pull request merged**
