### PR TITLE
#192 - no blocking operations on incremental update

### PR DESCRIPTION
**Pull request by olenagerasimova**
Restructured `Rpm#updateBatchIncrementally` to get rid of blocking operations for #192.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#216](https://github.com/artipie/rpm-adapter/issues/216) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3f274e12-bb78-4da1-8b0c-73490e4040e4); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I see that you unassigned this issue; the order is still assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
This pull request [#216](https://github.com/artipie/rpm-adapter/issues/216) is assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/432b1e6c-6440-4b8b-91c2-84a8a9ae2356); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@olegmoz changes look massive because I've extracted repeating code to methods, but ok, I can inline these methods back. The idea of the PR is not use `blockingGet` on storage operations.

**Comment by olenagerasimova** [comment]
@g4s8 please, could you take a look and merge?

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0cf2aef6-3274-4e83-b020-be89b679901f, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-boosts.xsl says: The boost for job "gh:artipie/rpm-adapter#216" exists in boosts.xml, but the job is absent in the WBS among 48 jobs.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [54af8b1d-e683-4768-9432-5acc701745ec](https://www.0crat.com/footprint/CT2E6TK9B/54af8b1d-e683-4768-9432-5acc701745ec), Type: "Remove job from WBS"

**Comment by sereshqua** [comment]
@olegmoz please make sure you will find at least 3 issues during next CR, thanks

**Comment by sereshqua** [comment]
@olegmoz ping

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable  ([here](https://github.com/artipie/rpm-adapter/issues/216#issuecomment-639099832))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ca467921-5714-4665-aa83-dab65ec69cb4, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.cost.pay_cash
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: Failed to add transaction
com.zerocracy.pm.cost.Ledger[133] java.io.IOException: Failed to add transaction
org.postgresql.jdbc.PgConnection[767] org.postgresql.util.PSQLException: This connection has been closed.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [76d92645-2af7-4dcd-ac13-ccc6f964c918](https://www.0crat.com/footprint/CT2E6TK9B/76d92645-2af7-4dcd-ac13-ccc6f964c918), Type: "Pay cash"

**Pull request merged**
