### PR TITLE
For #178 incremental update

### PR DESCRIPTION
**Pull request by olenagerasimova**
For #178: 
- added new method to Gzip to unpack xml.gz and test
- corrected `ModifiableRepository` to parse rmp if necessary
- added methods to `Rpm` and todo to continue
- extended `RpmITCase`

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@g4s8 please could you ask 0crat to elect reviewer for this PR?

**Comment by 0crat** [comment]
This pull request [#181](https://github.com/artipie/rpm-adapter/issues/181) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fdd70244-7bb3-4022-a7fb-a24177cfa8c0); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@olenagerasimova please resolve conflicts and we can merge

**Comment by jeffzhu503** [comment]
What is the **performance result** after you made this check-in?  How do you measure the performance? where do you publish the results?

**Comment by olenagerasimova** [comment]
@jeffzhu503 work on incremental update is not finished yet - there is no point on measuring/publishing any results yet. 
Also, please, if you'd like to get some answer, mention the person (or persons) your comment is addressed to. 
@g4s8 I've resolved conflicts.

**Comment by olenagerasimova** [comment]
@g4s8 could you please merge this? I've resolved conflicts once more

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#181](https://github.com/artipie/rpm-adapter/issues/181), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@771b26b8-67e1-41d2-9b59-49db76911c64, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#181] declared for identity constraint of element "speed".
```

[0.53.14](https://github.com/zerocracy/farm): CID: [79642759-84e8-4c76-bdbd-fcd300d866f0](https://www.0crat.com/footprint/CT2E6TK9B/79642759-84e8-4c76-bdbd-fcd300d866f0), Type: "Order was canceled"

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
