### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated http, ppom and asto versions, used permission actions and fixed build.

### CODE REVIEW

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks

**Comment by olenagerasimova** [comment]
@rultor release, tag=`1.2.1`

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#364` is not assigned, can't get performer

**Comment by olenagerasimova** [comment]
@rultor release, tag=`1.2.1`

**Comment by olegmoz** [comment]
@rultor release, tag=`1.2.1`

**Comment by olegmoz** [comment]
@olenagerasimova could you please re-try the release with updated ppom `0.4.1`

**Comment by olenagerasimova** [comment]
@olegmoz sure, but I think we also should merge https://github.com/artipie/rpm-adapter/pull/367

**Comment by olenagerasimova** [comment]
@rultor release, tag=`1.2.1`

**Pull request merged**
