### PR TITLE
#63 - add tests for repomd and todos

### PR DESCRIPTION
**Pull request by victornoel**
This is for #63. I also fixed two little bugs found previously and that would prevent the test to pass (see #65)

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#67](https://github.com/artipie/rpm-adapter/issues/67) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/842363fd-052b-4ccf-a586-84e4d2ee634f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by victornoel** [comment]
@Vatavuk please wait, I have to make some changes because I misunderstood the scope of the issue

**Comment by victornoel** [comment]
@Vatavuk I'm closing this, `Repomd` was meant to have been deleted, cf https://github.com/artipie/rpm-adapter/issues/63#issuecomment-608502266

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Pull request [#67](https://github.com/artipie/rpm-adapter/issues/67) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
