### PR TITLE
#319 - Access test resources via class-loader

### LINKED ISSUE #319: Access test resources via class-loader
This repository has a lot of test resources references via path instead of class-loader of current thread context. Fix it and possible replace code duplication by introducing corresponding classes/methods in test scope.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #319: access test resources via class-loader

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/327#issuecomment-655058275))

@olenagerasimova Job `gh:artipie/rpm-adapter#327` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/327#issuecomment-655058275))

@olenagerasimova Pull request [#327](https://github.com/artipie/rpm-adapter/issues/327) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by olenagerasimova** [comment]
@olegmoz conflicts resolved, please approve once more

**Pull request merged**
