### PR TITLE
#206 - corrected MetadataFileTest

### PR DESCRIPTION
**Pull request by olenagerasimova**
For #206 I've corrected test and coverages.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#207](https://github.com/artipie/rpm-adapter/issues/207) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/df7cbe84-91f3-4106-a81f-6abf2eb695d1); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@olenagerasimova The test is ok, the problem is in `MetadataFile`

**Comment by olenagerasimova** [comment]
@paulodamaso I do not see what's wrong(( This is repomd.xml generated in this test:
```
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo">
    <revision>1590686397179</revision>
    <data type="primary">
        <checksum type="sha">6d2fa03edc1a059325a0cd2b8d0bd6158c5eb10c</checksum>
        <open-checksum type="sha">7fe70820e08a1aac0ef224d9c66ab66831cc4ab1</open-checksum>
        <location href="repodata/c808ce6995fce264078e36411b35c6e32917f9ca-primary.xml.gz"/>
        <size>28</size>
        <open-size>8</open-size>
    </data>
</repomd>
``` 
I also checked repomd generated in `RpmITCase`, seems ok too.

**Comment by olenagerasimova** [comment]
@paulodamaso thanks for noticing the error, I've fixed `NamingPolicy` to use `FileChecksum` for calculating hex and created #208.

**Review by paulodamaso — DISMISSED** [review]
@olenagerasimova Great, thanks!

**Comment by paulodamaso** [comment]
@g4s8 please merge

**Comment by olenagerasimova** [comment]
@g4s8 please, could you merge this?

**Review by g4s8 — APPROVED** [review]

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@paulodamaso please make sure you will find at least 3 issues during next CR, thanks

**Comment by paulodamaso** [comment]
@sereshqua I will, thank you

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
